name: caravelle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.1
  font_awesome_flutter: ^10.4.0
  android_intent_plus: ^6.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  image_picker: ^1.2.0
  permission_handler: ^11.3.1
  country_picker: ^2.0.16
  smooth_page_indicator: ^1.1.0
  phone_number_hint: ^0.0.6
  phone_number_picker: ^0.0.8
  flutter_native_splash: ^2.4.6
  introduction_screen: ^4.0.0
  http: ^1.5.0
  carousel_slider: ^5.1.1
  flutter_screenutil: ^5.9.3
  local_auth: ^2.3.0
  connectivity_plus: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.3.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # -------- APP ICON SETUP --------
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/caravelle_512.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/caravelle_512.png

  # -------- CUSTOM FONTS --------
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
